import { randomUUID } from "node:crypto"
import { createReadStream } from "node:fs"
import fs from "node:fs/promises"
import path from "node:path"

export function uploadDir(): string {
  return path.resolve(/*turbopackIgnore: true*/ process.env.UPLOAD_DIR ?? "./data/uploads")
}

export function maxUploadBytes(): number {
  const mb = Number(process.env.MAX_UPLOAD_MB ?? 50)
  return (Number.isFinite(mb) && mb > 0 ? mb : 50) * 1024 * 1024
}

function resolveKey(key: string): string {
  // Keys are generated by us (UUIDs), but never trust data coming back from
  // an import file.
  if (!/^[a-zA-Z0-9-]{8,64}$/.test(key)) throw new Error("Invalid storage key")
  return path.join(/*turbopackIgnore: true*/ uploadDir(), key)
}

export function newStorageKey(): string {
  return randomUUID()
}

export async function writeStoredFile(key: string, data: Uint8Array): Promise<void> {
  await fs.mkdir(uploadDir(), { recursive: true })
  await fs.writeFile(resolveKey(key), data)
}

export async function storedFileExists(key: string): Promise<boolean> {
  try {
    await fs.access(resolveKey(key))
    return true
  } catch {
    return false
  }
}

export async function readStoredFile(key: string): Promise<Buffer | null> {
  try {
    return await fs.readFile(resolveKey(key))
  } catch {
    return null
  }
}

export async function statStoredFile(key: string) {
  try {
    return await fs.stat(resolveKey(key))
  } catch {
    return null
  }
}

export function openStoredFileStream(key: string, range?: { start: number; end: number }) {
  return createReadStream(resolveKey(key), range)
}

export async function deleteStoredFiles(keys: (string | null | undefined)[]): Promise<void> {
  await Promise.all(
    keys.filter((k): k is string => Boolean(k)).map(async (key) => {
      try {
        await fs.unlink(resolveKey(key))
      } catch {
        // Already gone — nothing to do.
      }
    }),
  )
}

export function attachmentKindForMime(mime: string): "image" | "audio" | "file" {
  if (mime.startsWith("image/")) return "image"
  if (mime.startsWith("audio/")) return "audio"
  return "file"
}
